version: '3.0'

services:
  database:
    image: 'postgres:11.8-alpine'
    container_name: rossini_postgres
    env_file:
      - database.env
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    expose:
      - 5432

volumes:
  database-data:
